// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SetGlobalVersion
{
	internal sealed partial class Vsix
	{
		public const string Id = "SetGlobalVersion.ca80294a-08df-4b04-857e-795dca8891db";
		public const string Name = "SetGlobalVersion";
		public const string Description = @"Empty VSIX Project.";
		public const string Language = "en-US";
		public const string Version = "1.0";
		public const string Author = "Eigil Krogh Sorensen";
		public const string Tags = "";
	}
}
