// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SetGlobalVersion
{
	internal sealed partial class Vsix
	{
		public const string Id = "SetGlobalVersion.59a022c9-e3e7-4d43-a852-7ebec1483e85";
		public const string Name = "SetGlobalVersion";
		public const string Description = @"Empty VSIX Project.";
		public const string Language = "en-US";
		public const string Version = "6.1";
		public const string Author = "Eigil Krogh Sorensen";
		public const string Tags = "";
	}
}
