// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SetGlobalVersion
{
    internal sealed partial class Vsix
    {
        public const string Id = "SetGlobalVersion.59a022c9-e3e7-4d43-a852-7ebec1483e85";
        public const string Name = "SetGlobalVersion";
        public const string Description = @"Set Global Version (Set same version numbers in all projects).";
        public const string Language = "en-US";
        public const string Version = "4.1";
        public const string Author = "Eigil Krogh Sorensen";
        public const string Tags = "global, version, solution-wide";
    }
}
