// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace SetGlobalVersion
{
	/// <summary>
	/// Helper class that exposes all GUIDs used across VS Package.
	/// </summary>
	internal sealed partial class PackageGuids
	{
		public const string SetGlobalVersionString = "5e28e511-47d4-4680-90d2-ce29df3cf318";
		public static Guid SetGlobalVersion = new Guid(SetGlobalVersionString);
	}
	/// <summary>
	/// Helper class that encapsulates all CommandIDs uses across VS Package.
	/// </summary>
	internal sealed partial class PackageIds
	{
		public const int MyCommand = 0x0100;
	}
}