// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SetGlobalVersion
{
    internal sealed partial class Vsix
    {
        public const string Id = "SetGlobalVersion.E306CB18-2CB7-44F4-AE99-EB5D176E3C64";
        public const string Name = "SetGlobalVersion_2019";
        public const string Description = @"Set Global Version (Set same version numbers in all projects).";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Eigil Krogh Sorensen";
        public const string Tags = "";
    }
}
