// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SetGlobalVersion
{
    internal sealed partial class Vsix
    {
        public const string Id = "SetGlobalVersion.4C416127-0E63-42C7-961B-586D48D46A3C";
        public const string Name = "SetGlobalVersion_2019";
        public const string Description = @"Set Global Version (Set same version numbers in all projects).";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Eigil Krogh Sorensen";
        public const string Tags = "";
    }
}
