// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SetVersionNumberGloballyXam
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SetVersionNumberGloballyXamString = "fdf55875-ca53-484e-b6ff-7c1acdfdde88";
        public static Guid SetVersionNumberGloballyXam = new Guid(SetVersionNumberGloballyXamString);

        public const string uiContextSupportedFlavorsString = "65302c28-e96f-4a6d-9669-e6cb52e3d781";
        public static Guid uiContextSupportedFlavors = new Guid(uiContextSupportedFlavorsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
    }
}